-- ============================================================
-- BANCO DE TESTE do AutoStock (NÃO rodar no banco do grupo!)
-- Cria as tabelas do sistema com a mesma estrutura do banco real,
-- copia as 5 peças e gera movimentações de exemplo dos últimos 90 dias.
-- Como usar: projeto de teste > SQL Editor > New query > cole tudo > Run
-- ============================================================

-- 1) PEÇAS (mesmas colunas do banco do grupo)
create table if not exists public.pecas (
  id                bigint generated by default as identity primary key,
  sku               text,
  nome              text not null,
  categoria         text,
  quantidade_atual  integer not null default 0,
  estoque_minimo    integer not null default 0,
  preco_venda       numeric(12,2) not null default 0,
  ean               text,
  localizacao       text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz default now()
);

-- 2) MOVIMENTAÇÕES (entradas e saídas)
create table if not exists public.movimentacoes (
  id              bigint generated by default as identity primary key,
  peca_id         bigint not null references public.pecas(id) on delete cascade,
  tipo_movimento  text not null check (tipo_movimento in ('entrada', 'saida')),
  quantidade      integer not null check (quantidade > 0),
  data_hora       timestamptz not null default now(),
  documento       text,
  motivo          text,
  usuario_id      uuid
);

-- 3) ORÇAMENTOS (o mesmo SQL do arquivo orcamentos.sql)
create table if not exists public.orcamentos (
  id          bigint generated by default as identity primary key,
  cliente     text not null,
  desconto    numeric(5,2) not null default 0 check (desconto >= 0 and desconto <= 100),
  status      text not null default 'aberto' check (status in ('aberto', 'aprovado', 'cancelado')),
  validade    date not null default (current_date + 7),
  observacao  text,
  created_at  timestamptz not null default now()
);

create table if not exists public.orcamento_itens (
  id              bigint generated by default as identity primary key,
  orcamento_id    bigint not null references public.orcamentos(id) on delete cascade,
  peca_id         bigint not null references public.pecas(id),
  quantidade      integer not null check (quantidade > 0),
  preco_unitario  numeric(12,2) not null default 0 check (preco_unitario >= 0)
);
create index if not exists orcamento_itens_orcamento_idx on public.orcamento_itens (orcamento_id);

-- 4) PERMISSÕES: o app usa a chave pública (anon), igual ao banco do grupo
alter table public.pecas            enable row level security;
alter table public.movimentacoes    enable row level security;
alter table public.orcamentos       enable row level security;
alter table public.orcamento_itens  enable row level security;

drop policy if exists "teste acesso app" on public.pecas;
create policy "teste acesso app" on public.pecas for all to anon, authenticated using (true) with check (true);
drop policy if exists "teste acesso app" on public.movimentacoes;
create policy "teste acesso app" on public.movimentacoes for all to anon, authenticated using (true) with check (true);
drop policy if exists "orcamentos acesso app" on public.orcamentos;
create policy "orcamentos acesso app" on public.orcamentos for all to anon, authenticated using (true) with check (true);
drop policy if exists "orcamento_itens acesso app" on public.orcamento_itens;
create policy "orcamento_itens acesso app" on public.orcamento_itens for all to anon, authenticated using (true) with check (true);

-- 5) DADOS: as mesmas 5 peças do banco do grupo (só entra se a tabela estiver vazia)
insert into public.pecas (sku, nome, categoria, quantidade_atual, estoque_minimo, preco_venda)
select * from (values
  ('TESTE',    'tes',                                            'Combustão', 0,   2,  123.00),
  ('REC - 123','RECEBA',                                         'Combustão', 126, 5,  67.00),
  ('PST-2041', 'Pastilha de Freio Dianteira Cerâmica Bosch Pro', 'Combustão', 24,  15, 98.00),
  ('DSC-1090', 'Disco de Freio Ventilado 280mm Brembo',          'Combustão', 12,  10, 185.00),
  ('FLT-5011', 'Filtro de Óleo Blindado Mahle OC-600',           'Combustão', 45,  20, 24.50)
) as v(sku, nome, categoria, quantidade_atual, estoque_minimo, preco_venda)
where not exists (select 1 from public.pecas);

-- 6) MOVIMENTAÇÕES DE EXEMPLO: saídas nos últimos 90 dias (para a Previsão IA ter dados)
--    Só entra se ainda não houver movimentações.
insert into public.movimentacoes (peca_id, tipo_movimento, quantidade, data_hora, documento, motivo)
select p.id,
       'saida',
       1 + floor(random() * 3)::int,
       now() - (d || ' days')::interval - (floor(random() * 10) || ' hours')::interval,
       'OS-' || (4000 + d),
       'Balcão'
from public.pecas p
cross join generate_series(0, 89) as d
where p.sku in ('PST-2041', 'DSC-1090', 'FLT-5011')
  and random() < case p.sku when 'FLT-5011' then 0.55 when 'PST-2041' then 0.40 else 0.25 end
  and not exists (select 1 from public.movimentacoes);

-- algumas entradas de fornecedor
insert into public.movimentacoes (peca_id, tipo_movimento, quantidade, data_hora, documento, motivo)
select p.id, 'entrada', 20, now() - (d || ' days')::interval, 'NF-e ' || (12000 + d), 'Fornecedor'
from public.pecas p
cross join (values (75), (45), (15)) as dias(d)
where p.sku in ('PST-2041', 'FLT-5011')
  and (select count(*) from public.movimentacoes where tipo_movimento = 'entrada') = 0;

-- Conferência: deve mostrar 5 peças e várias movimentações
select (select count(*) from public.pecas) as pecas,
       (select count(*) from public.movimentacoes) as movimentacoes,
       (select count(*) from public.orcamentos) as orcamentos;
