-- ============================================================
-- FINANCEIRO - livro caixa do AutoStock
-- Como usar: Supabase > SQL Editor > New query > cole tudo > Run
-- (pode rodar mais de uma vez sem problema)
--
-- As VENDAS não precisam ser lançadas aqui: o sistema calcula sozinho
-- a partir das saídas de estoque (quantidade x preço de venda da peça).
-- Aqui ficam os outros movimentos de dinheiro: compras de peças,
-- aluguel, salários, contas, impostos, outras receitas e o saldo inicial.
-- ============================================================

create table if not exists public.caixa (
  id          bigint generated by default as identity primary key,
  tipo        text not null check (tipo in ('entrada', 'saida')),
  categoria   text not null,
  descricao   text not null,
  valor       numeric(12,2) not null check (valor > 0),
  data        date not null default current_date,
  usuario_id  uuid default auth.uid(),
  created_at  timestamptz not null default now()
);

create index if not exists caixa_data_idx on public.caixa (data);

-- Permissões (RLS): igual às outras tabelas do sistema
alter table public.caixa enable row level security;

drop policy if exists "caixa acesso app" on public.caixa;
create policy "caixa acesso app" on public.caixa
  for all to anon, authenticated using (true) with check (true);

-- Conferência
select count(*) as lancamentos_no_caixa from public.caixa;
