-- ============================================================
-- ORÇAMENTOS - tabelas novas para o AutoStock
-- Como usar: Supabase > SQL Editor > New query > cole tudo > Run
-- (pode rodar mais de uma vez sem problema)
-- ============================================================

-- 1) Cabeçalho do orçamento
create table if not exists public.orcamentos (
  id          bigint generated by default as identity primary key,
  cliente     text not null,
  desconto    numeric(5,2) not null default 0 check (desconto >= 0 and desconto <= 100),
  status      text not null default 'aberto' check (status in ('aberto', 'aprovado', 'cancelado')),
  validade    date not null default (current_date + 7),
  observacao  text,
  created_at  timestamptz not null default now()
);

-- 2) Itens (peças) de cada orçamento
create table if not exists public.orcamento_itens (
  id              bigint generated by default as identity primary key,
  orcamento_id    bigint not null references public.orcamentos(id) on delete cascade,
  peca_id         bigint not null references public.pecas(id),
  quantidade      integer not null check (quantidade > 0),
  preco_unitario  numeric(12,2) not null default 0 check (preco_unitario >= 0)
);

create index if not exists orcamento_itens_orcamento_idx on public.orcamento_itens (orcamento_id);

-- 3) Permissões (RLS)
-- O sistema ainda não tem login, então liberamos para a chave pública (anon),
-- do mesmo jeito que as tabelas "pecas" e "movimentacoes" precisam estar.
-- Quando o grupo criar o login, troque "anon" por "authenticated".
alter table public.orcamentos enable row level security;
alter table public.orcamento_itens enable row level security;

drop policy if exists "orcamentos acesso app" on public.orcamentos;
create policy "orcamentos acesso app" on public.orcamentos
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "orcamento_itens acesso app" on public.orcamento_itens;
create policy "orcamento_itens acesso app" on public.orcamento_itens
  for all to anon, authenticated using (true) with check (true);
